name: SauceLinkExample
options:
  bundleIdPrefix: com.saucelink
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  SauceLink:
    path: ../

targets:
  SauceLinkExample:
    type: application
    platform: iOS
    sources:
      - path: SauceLinkExample
        type: group
    dependencies:
      - package: SauceLink
    settings:
      base:
        INFOPLIST_FILE: SauceLinkExample/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.saucelink.example
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: SauceLinkExample/Info.plist
      properties:
        CFBundleDisplayName: SauceLink Example
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleURLTypes:
          - CFBundleURLName: com.saucelink.example
            CFBundleURLSchemes:
              - saucelinkexample
        LSApplicationQueriesSchemes:
          - saucelinkexample

